data:
  train_files: data/vqa_mcq_840
  val_files: None
  prompt_key: problem
  max_prompt_length: 1500
  max_response_length: 2000
  rollout_batch_size: 32
  shuffle: true
  seed: 42
  max_pixels: 12845056
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 32
    micro_batch_size_per_device_for_update: 8
    micro_batch_size_per_device_for_experience: 8
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    model:
      model_path: pretrained_models/Qwen2-VL-2B-Instruct
      enable_gradient_checkpointing: true
    optim:
      lr: 2.0e-6
      weight_decay: 1.0e-2
    fsdp:
      param_offload: false
      optimizer_offload: false
      torch_dtype: null
    offload:
      param_offload: false
      optimizer_offload: false

  rollout:
    temperature: 1.0
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.85
    n: 16
    enable_chunked_prefill: true

  ref:
    offload:
      param_offload: false

  reward:
    reward_type: function
    compute_score: vqa_mcq

trainer:
  total_episodes: 1
  logger: ["console", "wandb"]
  project_name: vqa_mcq_2b
  n_gpus_per_node: 1
  nnodes: 1
  save_freq: 50
  test_freq: 100000
  val_before_train: false
  val_only: false
